INSERT INTO SYSTEM_USERS (ID, NAME, EMAIL) VALUES (USER_SEQ.nextval, 'USER TEST 1', 'test1@email.com');
INSERT INTO SYSTEM_USERS (ID, NAME, EMAIL) VALUES (USER_SEQ.nextval, 'USER TEST 2', 'test2@email.com');
INSERT INTO SYSTEM_USERS (ID, NAME, EMAIL) VALUES (USER_SEQ.nextval, 'USER TEST 3', 'test3@email.com');
INSERT INTO SYSTEM_USERS (ID, NAME, EMAIL) VALUES (USER_SEQ.nextval, 'USER TEST 4', 'test4@email.com');